### ISSUE TITLE
Everything times out

### ISSUE THREAD

**Issue by nickmcdonnough** [remoteinterview/compilebox#4] opened 2014-10-07 22:10 UTC
Hey,

I've installed everything following the instructions in the readme but all tests of the language timeout. I installed compilebox on a DigitalOcean instance with 2gigs of RAM which should be sufficient. 

This is as far as I'm getting.

```
Listening at 80
Python file was saved!
Input file was saved!
/root/API/DockerTimeout.sh 15s -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' -i -t -v  "/root/API/temp/016d76e1fbe201279745":/usercode virtual_machine /usercode/script.sh python file.py
------------------------------
ATTEMPTING TO REMOVE: temp/016d76e1fbe201279745
------------------------------
Timed Out: temp/016d76e1fbe201279745 Python
Time:
undefined
```

**Comment by zengfany** [comment] 2015-01-09 06:46
I am running it from Mac env and facing the same issue, it is caused by missing 'timeout' shell command in the NodeJS server env. DockerTimeout.sh called by NodeJS server will kill docker container immediately after launched it when 'timeout' command not found, so if the build inside the container is not finished however the container is killed, the NodeJS will response timeout to the web client.

**Comment by jjmpsp** [comment] 2015-02-15 16:55
+1 also facing this same issue (on mac)

@zengfany is right. This can be fixed on mac by installing CoreUtils ```brew install coreutils```and gtimeout can be used instead of the timeout function. 

I've been debugging the script(s) for 5 hours now, but still can't find out where the exact problem lies. I'll perform some more tests on a different OS and update if I can find a fix.

**Comment by jjmpsp** [comment] 2015-02-19 23:06
Update: Finally got this script working after 5 whole days of debugging! Will put together some instructions tomorrow and update.

**Comment by kristina-hager** [comment] 2015-03-04 20:51
@RyanNutt  - I am planning to take the same approach, i.e. run "the official docker images for each language - a different image for each "

Did this approach keep working out for you?

Just to avoid reinventing the code, do you have any code changes you could share?

**Comment by RyanNutt** [comment] 2015-03-04 20:57
It's working pretty well, but I started from scratch so it's not just code changes to compilebox.

**Comment by kristina-hager** [comment] 2015-03-04 22:32
@RyanNutt , thanks. I will keep trying for now to make compilebox work for at least one language. Although, who knows, I may end up needing to abandon and start from scratch at some point!

**Comment by twz915** [comment] 2015-05-04 01:18
I don't know why 404?
$ sudo ./UpdateDocker.sh 

Creating Docker Image
Sending build context to Docker daemon 3.584 kB
Sending build context to Docker daemon 
Step 0 : FROM virtual_machine
Pulling repository virtual_machine
2015/05/04 09:17:33 HTTP code: 404
Retrieving Installed Docker Images
REPOSITORY            TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>                <none>              e6fc6ac28789        4 days ago          1.175 GB
chug/ubuntu14.04x64   latest              81b68b976893        11 months ago       224.7 MB

**Comment by Gouthamve** [comment] 2015-06-06 15:36
I am facing this on my mac, but it is working fine on my 512MB Ubuntu Droplet on DO. I just followed their instructions.

**Comment by jayeshcp** [comment] 2015-06-09 15:19
Followed instructions correctly, Ubuntu 15.04, getting timeout:
```
Python file was saved!
Input file was saved!
/opt/compilebox/DockerTimeout.sh 20s -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' -i -t -v  "/opt/compilebox/temp/d1d5c05d47a4590320c8":/usercode virtual_machine /usercode/script.sh python file.py  
------------------------------
ATTEMPTING TO REMOVE: temp/d1d5c05d47a4590320c8
------------------------------
Timed Out: temp/d1d5c05d47a4590320c8 Python
Time: 
undefined
```

**Comment by madguy02** [comment] 2015-06-12 11:28
I am facing the same problem ,who do i resolve it?? is it actually a memory problem or an installation error,?Should i try it with a single language?

**Comment by Gouthamve** [comment] 2015-06-12 11:41
No its not a memory problem. The thing is the following line 
```bash
/opt/compilebox/DockerTimeout.sh 20s -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' -i -t -v  "/opt/compilebox/temp/d1d5c05d47a4590320c8":/usercode virtual_machine /usercode/script.sh python file.py
```
Which is executed returns an error and doesn't execute at all.

Just quit the program (ctrl+C) before the timeout finishes (Because the temp file is deleted) and run it and try to debug. On a Mac it is the fact that ```timeout``` command doesn't exist.

**Comment by madguy02** [comment] 2015-06-17 03:35
hello guys...i am actually trying to run compilebox on my vmware 11...the error which i am facing right now are most probably networking errors that the vm ware restricts certain accesses to the slave OS.
check this out:"Get https://index.docker.io/v1/repositories/chug/ubuntu14.04x64/images: dial tcp: lookup index.docker.io on [127.0.1.1]:53: server misbehaving"

can anyone help me on this how to resolve this particular problem

**Comment by saru95** [comment] 2015-09-03 19:54
1. I am running ./UpdateDocker.sh , then going to API folder and running ``` node app.js``` .
Am I doing it right ? I'm running a Mac . How to launch docker while in in API folder ?
Also whats the replacement for timeout command in Mac ?

**Comment by x956606865** [comment] 2015-12-18 13:36
It seems sometimes the UpdateDocker.sh won't generate the image "virtual_machine",you sholud use "sudo docker ps -a" find the latest image id and "sudo commit yourID virtual_machine:latest",if it doesn't work.you can also change some codes in "DockerSandbox.js" such as remove the patten "  -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' " if you needn't.If it steel doesn't work,may be you shold get into the image and try those orders by typing,finding that if anything doesn't being installed.At least when I try to do this,I find the "bc" is not been installed,so I install it and commit again.I changed many codes,so it ad least worked.I'm not good at English,sorry for some mistakes.

**Comment by meashish123** [comment] 2016-03-21 16:41
I was facing the same issue.
- First, I was behind a http proxy, therefore I had to update the 'dockerfile' to add http_proxy variable in every line (Now the image 'virtual_machine' generated successfully).
- Also, keep in mind that you also have to run Nodejs application as sudo. 
'sudo node app.js'.

That finally solved the problem for me.

**Closed** 2016-06-17 16:03 UTC

**Comment by rvpradeep** [comment] 2017-02-10 19:30
I had the same problem on OSX. I fixed it as follows:

1)  Installing CoreUtils 
`brew install coreutils`
2) In line 8 of DockerTimeout.sh change `timeout` to `gtimeout`

**Comment by saurabh1294** [comment] 2017-09-02 13:02
Hi All,

I think timeout in most cases is because of the docker image not getting created. 
Below is the output from UpdateDocker.sh on Cent OS 6.9. I am also getting timeout error when trying to compile/run from the web interface. Can anyone suggest a solution for this ?


./UpdateDocker.sh
Creating Docker Image
Sending build context to Docker daemon 4.096 kB
Sending build context to Docker daemon
Step 0 : FROM chug/ubuntu14.04x64
 ---> 81b68b976893
Step 1 : MAINTAINER ASAD MEMON, OSMAN ALI
 ---> Using cache
 ---> 4ecf3c179ac6
Step 2 : RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
 ---> Using cache
 ---> 10d063d4d7b7
Step 3 : RUN apt-get update
 ---> Using cache
 ---> 265848ac1b02
Step 4 : RUN apt-get install -y gcc
 ---> Using cache
 ---> 9e96afb4acd5
Step 5 : RUN apt-get install -y g++
 ---> Using cache
 ---> 0fa5fa6f42de
Step 6 : RUN apt-get install -y php5-cli
 ---> Using cache
 ---> 7470c0b0a2c6
Step 7 : RUN apt-get install -y ruby
 ---> Using cache
 ---> 0e4f149df0d0
Step 8 : RUN apt-get install -y python
 ---> Using cache
 ---> c4ccba10670b
Step 9 : RUN apt-get install -y mono-xsp2 mono-xsp2-base
 ---> Using cache
 ---> 045d45bb5131
Step 10 : RUN apt-get install -y mono-vbnc
 ---> Using cache
 ---> 6d9233824386
Step 11 : RUN apt-get install -y npm
 ---> Using cache
 ---> 8b6aa5cd0ea2
Step 12 : RUN apt-get install -y golang-go
 ---> Using cache
 ---> 92abee3360b1
Step 13 : RUN apt-get install -y nodejs
 ---> Using cache
 ---> 5ec842c4a19f
Step 14 : RUN npm install -g underscore request express jade shelljs passport http sys jquery lodash async mocha moment connect validator restify ejs ws co when helmet wrench brain mustache should backbone forever  debug && export NODE_PATH=/usr/local/lib/node_modules/
 ---> Using cache
 ---> a8dfd4a01824
Step 15 : RUN apt-get install -y clojure1.4
 ---> Using cache
 ---> 9da9b979c243
Step 16 : RUN apt-get install -y python-software-properties
 ---> Using cache
 ---> 823da680e4eb
Step 17 : RUN apt-get install -y software-properties-common
 ---> Using cache
 ---> 005f4dc2f7aa
Step 18 : RUN add-apt-repository -y ppa:webupd8team/java
 ---> Using cache
 ---> ec8f4b6f7448
Step 19 : RUN apt-get update
 ---> Using cache
 ---> 6db491eb6877
Step 20 : RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
 ---> Using cache
 ---> bbc9077ed378
Step 21 : RUN apt-get install -y oracle-java7-installer
 ---> Running in 69f11ec0b8bd
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  gsfonts gsfonts-x11 libfontenc1 libxfont1 wget x11-common xfonts-encodings
  xfonts-utils
Suggested packages:
  visualvm ttf-baekmuk ttf-unfonts ttf-unfonts-core ttf-kochi-gothic
  ttf-sazanami-gothic ttf-kochi-mincho ttf-sazanami-mincho ttf-arphic-uming
  firefox firefox-2 iceweasel mozilla-firefox iceape-browser mozilla-browser
  epiphany-gecko epiphany-webkit epiphany-browser galeon midbrowser
  moblin-web-browser xulrunner xulrunner-1.9 konqueror chromium-browser midori
  google-chrome
The following NEW packages will be installed:
  gsfonts gsfonts-x11 libfontenc1 libxfont1 oracle-java7-installer wget
  x11-common xfonts-encodings xfonts-utils
install -y oracle-java7-installer
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libf/libfontenc/libfontenc1_1.1.2-1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libx/libxfont/libxfont1_1.4.7-1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.15-1ubuntu1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/pool/main/o/oracle-java7-installer/oracle-java7-installer_7u80+7u60arm-0~webupd8~1_all.deb  Could not resolve 'ppa.launchpad.net'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gsfonts/gsfonts_8.11+urwcyr1.0.7~pre44-4.2ubuntu1_all.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/xorg/x11-common_7.7+1ubuntu8_all.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-encodings/xfonts-encodings_1.0.4-1ubuntu1_all.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/xfonts-utils/xfonts-utils_7.7+1_amd64.deb  Could not resolve 'archive.ubuntu.com'

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/g/gsfonts-x11/gsfonts-x11_0.22_all.deb  Could not resolve 'archive.ubuntu.com'

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
